services:
  mariadb:
    image: mariadb:10.11
    container_name: clima_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: clima_tcc
      MYSQL_USER: clima_user
      MYSQL_PASSWORD: clima_pass
    volumes:
      - ./docker/mariadb_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "3307:3306"

  php:
    build:
      context: ./docker/php
    container_name: clima_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public
      - ./database:/var/www/database
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_NAME: clima_tcc
      DB_USER: clima_user
      DB_PASS: clima_pass

  nginx:
    image: nginx:alpine
    container_name: clima_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php